import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '../styles/globals.css'
import { cn } from '@/lib/utils'
import { cookies } from 'next/headers'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	const cookieStore = await cookies()
	const theme = cookieStore.get('theme')?.value || 'system'

	return (
		<html lang="en">
			<body
				className={cn(
					`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen text-[#0E121B] dark:bg-neutral-950 bg-neutral-0`,
					{
						dark: theme === 'dark',
					}
				)}
			>
				{children}
			</body>
		</html>
	)
}
